### PR TITLE
feat (subscription docs) - add documentation for tos and pn metadata

### PR DESCRIPTION
**Pull request by jackiemunroe**
- add documentation for how we will be storing terms of service and privacy notice links in Stripe metadata

closes https://github.com/mozilla/fxa/issues/5583

### CODE REVIEW

**Comment by bbangert** [comment]
For emails, it looks like we might need to include a plain-text variant. What's the process for locating a plain-text version to embed?

**Comment by bbangert** [comment]
It looks like there's https://github.com/mozilla/legal-docs/tree/master/firefox_cloud_services_ToS that stores various translations of the ToS. I'm not clear on whether we serve these documents up or not (does another group run this service?). Will the URL's we get from Stripe in the metadata allow us to get the plain-text version with Content-Type of text/plain? Can we use the Accept header to get the right translation?

**Comment by lmorchard** [comment]
> It looks like there's https://github.com/mozilla/legal-docs/tree/master/firefox_cloud_services_ToS that stores various translations of the ToS. I'm not clear on whether we serve these documents up or not (does another group run this service?).

In terms of the link, FPN terms are currently here on mozilla.org: https://www.mozilla.org/about/legal/terms/firefox-private-network

We use that link in emails. The fpn.firefox.com site links there, too. We could host them on FxA. IMO, probably better if the RP hosted them. In this case, it's neither. I'm not sure if / how the legal team updates that page on mozilla.org

> Will the URL's we get from Stripe in the metadata allow us to get the plain-text version with Content-Type of text/plain?

Depending on the outcome of meetings today, I guess either: a) we can just link to them or b) we might need additional metadata properties to identify the correct sources?

> Can we use the Accept header to get the right translation?

If we move these properties into the `product:` prefix, we can use that mechanism to key on locale. i.e.;

| Key              | Value                                                                |
| ---------------- | -------------------------------------------------------------------- |
|product:termsOfServiceURL:{locale} | The URL for the webpage containing the Terms of Service for the product offering|
|product:privacyNoticeURL:{locale} | The URL for the webpage containing the Privacy Notice for the product offering|

**Comment by bbangert** [comment]
> > Can we use the Accept header to get the right translation?
> 
> If we move these properties into the `product:` prefix, we can use that mechanism to key on locale from our side. i.e.;
> Key 	Value
> product:termsOfServiceURL 	Default URL for the webpage containing the Terms of Service for the product offering
> product:termsOfServiceURL:{locale} 	Localized override URL for the webpage containing the Terms of Service for the product offering
> product:privacyNoticeURL 	The URL for the webpage containing the Privacy Notice for the product offering
> product:privacyNoticeURL:{locale} 	Localized override URL for the webpage containing the Privacy Notice for the product offering

This sounds good to me. 👍

**Comment by jackiemunroe** [comment]
@bbangert @lmorchard Sorry about the delay! I've made the updates suggested. Could you give it another look over?

**Pull request merged**
